version: '3.4'

services:
  sonardb:
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
  sonarqube:
    image: sonarqube:alpine
    restart: always
    depends_on:
    - sonardb
    ports:
    - 9000:9000
    environment:
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/
    - SONARQUBE_JDBC_PASSWORD=${POSTGRES_PASSWORD}
    - SONARQUBE_JDBC_USERNAME=${POSTGRES_USER}